version: '3.6'

services:
  node:
    container_name: node_2
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    networks:
      - codernet


  mail:
    container_name: coder_mail_1
    restart: always
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    networks:
     - codernet


networks:
  codernet:
    driver: "bridge"