openapi: 3.0.0
info:
  title: API de Productos
  version: 1.0.0
paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Productos obtenidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  product:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  pagination:
                    type: object
                    properties:
                      totalDocs:
                        type: number
                      totalPages:
                        type: number
                      page:
                        type: number
                      limit:
                        type: number
      "500":
        description: Error del servidor

    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        "200":
          description: Producto creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "400":
          description: Solicitud incorrecta
        "500":
          description: Error del servidor
  /api/products/{id}:
    get:
      summary: Obtiene un producto por su id
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: Id del producto
        schema:
          type: string
      responses:
        "200":
          description: Producto obtenido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado
        "500":
          description: Error del servidor

    put:
      summary: Actualiza un producto existente
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: Id del producto
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: Producto actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado
        "500":
          description: Error del servidor

    delete:
      summary: Elimina un producto existente
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: Id del producto
        schema:
          type: string
      responses:
        "200":
          description: Producto eliminado
        "404":
          description: Producto no encontrado
        "500":
          description: Error del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        code:
          type: string
        price:
          type: number
        stock:
          type: number
        category:
          type: string
        thumbnail:
          type: string
        owner:
          type: string

    NewProduct:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        code:
          type: string
        price:
          type: number
        stock:
          type: number
        category:
          type: string
        thumbnail:
          type: string
        owner:
          type: string
